version: '3.7'
services:
  gk-nginx:
    container_name: gk-nginx
    image: nginx
    restart: always
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - gksocket:/tmp
    networks:
      - gknet
    depends_on:
      - gk-web
    ports:
      - 80:80
  gk-web:
    container_name: gk-web
    image: gk-web
    build: .
    networks:
      - gknet
    # ports: 소켓통신(80)을 하고 있기때문에 필요없음
    #   - 8080:8080
    # depends_on:
    #   - gk-db
    volumes:
      #- ./gogglekaap/static/user_images:/var/www/gogglekaap/gogglekaap/static/user_images:rw
      - ./:/var/www/gogglekaap
      - gksocket:/tmp
    restart: always
    environment:
      - FLASK_APP=gogglekaap
      - FLASK_ENV=${FLASK_ENV:-development}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    command: ['sh', './etc/docker-entrypoint.sh']
  
networks:
  gknet:

volumes:
  gksocket: