# docker-compose가 실행될 때 같이 run
version: '3.7'
services:
  gk-db:
      container_name: gk-db
      image: mysql:5.7
      networks:
        - gknet
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: gogglekaap
      command:
        - --character-set-server=utf8
        - --collation-server=utf8_unicode_ci
      volumes:
        - gkvolume:/var/lib/mysql
      restart: always
volumes:
  gkvolume: