"""empty message

Revision ID: f72efbd24c23
Revises: 120324369968
Create Date: 2023-03-31 16:46:54.795172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f72efbd24c23'
down_revision = '120324369968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linked_image', sa.String(length=200), nullable=True))
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memo', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('linked_image')

    # ### end Alembic commands ###
